[package]
name = "asciinema-relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
tokio = { version = "1.14.0", features = ["full"] }
# tokio = "1.14.0"
tokio-tungstenite = "0.16.0"
tungstenite = "0.16.0"
anyhow = "1.0"
futures-util = "0.3.18"
vt = { path = "../vt-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
atty = "0.2"
